### PR TITLE
Add CSS Day (Amsterdam), WebExpo

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
Hello! Great idea. Not sure if you need these payment terms to be stated publicly somewhere, but I’ve spoken at CSS Day, and will be speaking at WebExpo in September, and can confirm that both cover travel, accommodation and pay a speaking fee too. Hope this helps.

### CODE REVIEW

**Comment by abiggerhammer** [comment]
Thanks! I notice that neither CSS Day nor WebExpo appear to have open submissions. Can you confirm whether this is the case? I couldn't find a CFP link on either site. We've had several submissions like that, and I think it's enough to make them their own category.

**Comment by paulrobertlloyd** [comment]
Oh sorry, I didn’t see that open submission was a requirement. I’m not entirely sure, as I was invited to speak at both. I can ask the organisers, if you like?

**Comment by abiggerhammer** [comment]
No worries -- it hadn't actually occurred to me when I put the site together! I've added a section for cons that do pay but don't have open subs, and would appreciate your asking very much.

**Comment by paulrobertlloyd** [comment]
Re: WebExpo: “WebExpo currently doesn’t have open call for speakers. There was a concept tested two years ago where the public could suggest and vote on topics, and nominate and vote on speakers to cover the winning topics. But last two years it has been back to a curated format.”

Just need to follow up on CSS Day now.

**Comment by paulrobertlloyd** [comment]
…and CSS Day doesn’t have an open call for speakers, or at least not for the previous three editions.

**Pull request closed without merging**
